### ISSUE TITLE
`uploader_placeholder` session state initialization missing

### ISSUE THREAD

**Issue by asehmi** [reasonmethis/docdocgo-core#9]
https://github.com/reasonmethis/docdocgo-core/blob/1751f7225c808ca2573fdaed036442ba4f004085/utils/streamlit/prepare.py#L48

Suggest you add `st.session_state.uploader_placeholder = st.empty()` to this file before L48. If the app is started afresh and you run `/ingest new` straight away, an exception is thrown since `uploader_placeholder` isn't yet in session state.

**Comment by reasonmethis** [comment]
I couldn't reproduce this error:
<img width="941" alt="image" src="https://github.com/reasonmethis/docdocgo-core/assets/111213624/e6433629-6fdc-4ef8-82bd-4b76544a43d6">
I think the statement `files, allow_all_ext = show_uploader(border=False)` on L199 in streamlit_app.py makes sure that `uploader_placeholder` is always initialized before `/ingest new` can be executed.

I will still add a safeguard in `show_uploader`, since in your version the initial uploader doesn't appear by default, as it does in mine.

**Comment by asehmi** [comment]
Yes, in theory, but if `is_new_widget` is `True` then this throws:

```
    if is_new_widget:
        st.session_state.uploader_placeholder.empty()
```

Perhaps my merging of your changes missed something. 

I initially changed those lines to...

```
 if is_new_widget:
        st.session_state.uploader_placeholder = st.empty()
```

...then decided setting the session state var in the `utils/streamlit/prepare.py` was better.

**Comment by reasonmethis** [comment]
I have updated the code, and the current version should not be vulnerable to this issue even when the code is modified to not show the uploader right away.
